version: "3"
services:
  mongo-prod:
    image: mongo:latest
    ports:
      - "20717:20717" 
    volumes:
      - /data/db # Create a volume for the DB.
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8081
    restart: always
  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo-prod
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo-prod:27017/PROD
      - PORT=8081
      - HOST=localhost:3000
      - SENDGRID_API_KEY=<YOUR_KEY_HERE>
      - SENDING_EMAIL=<OPTIONAL_YOUR_SENDING_EMAIL_HERE>
      - SESSION_KEY=<YOUR_KEY_HERE>
    ports:
      - "8081:8081"
    restart: always